# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7dfbc14068f1a6c1c53935b2da823d12f7cc1f627b31e968d5f86bd3236966279cbd5e26646791c82e962a59d1b2202c1a49f4266f5b200f9e9d274ebf681157

test:
  secret_key_base: 667919b2658bea420aa1b08e8eafe5af069f6e2c164d4b99e66f43f4af2e7318b8fbff8c02ff9b64c811c2fee5bc839f239c5b93c093cbc0cfaab9d3ab281ec6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
